[package]
name = "animator"
version = "0.0.0"
edition = "2024"
license = "GPL-3.0-only"

[dependencies]
anyhow = "1.0.102"
geo = { version = "0.33.1", features = ["serde"] }
geo-types = "0.7.19"
image = "0.25.10"
imageproc = "0.26.1"
marching_squares = { path = "../marching_squares" }
oklab = "1.1.2"
ordered-float = "5.3.0"
rand = "0.10.1"
serde = "1.0.228"
serde_json = { version = "1.0.149", features = ["float_roundtrip"] }
tectonic = "0.16.9"
tempfile = "3.27.0"
tiny-skia = "0.12.0"
